<?xml version="1.0" encoding="UTF-8"?>
<CustomObjectTranslation xmlns="http://soap.sforce.com/2006/04/metadata">
    <layouts>
        <layout>Error Layout</layout>
        <sections>
            <label>Aangepaste Koppelingen</label>
            <section>Custom Links</section>
        </sections>
    </layouts>
    <nameFieldLabel>Foutnummer</nameFieldLabel>
    <standardFields>
        <name>Name</name>
        <label>Foutnummer</label>
    </standardFields>
    <gender>Feminine</gender>
    <caseValues>
        <plural>false</plural>
        <value>Fout</value>
    </caseValues>
    <caseValues>
        <plural>true</plural>
        <value>Fouten</value>
    </caseValues>
    <fields>
        <name>Context_Type__c</name>
        <help>Context die de fout gegenereerde, indien bekend.</help>
        <label>Contexttype</label>
    </fields>
    <fields>
        <name>Datetime__c</name>
        <help>Datum en tijd wanneer de fout is opgetreden</help>
        <label>Datum/Tijd</label>
    </fields>
    <fields>
        <name>Email_Sent__c</name>
        <help>Geeft aan of een e-mailnotificatie met betrekking tot deze fout is verzonden.</help>
        <label>E-mail Verzonden</label>
    </fields>
    <fields>
        <name>Error_Type__c</name>
        <help>Type fout die is opgetreden</help>
        <label>Fouttype</label>
    </fields>
    <fields>
        <name>Full_Message__c</name>
        <help>Volledige tekst van het foutbericht</help>
        <label>Volledig Bericht</label>
    </fields>
    <fields>
        <name>Object_Type__c</name>
        <help>Type object waarop de fout is opgetreden, indien bekend.</help>
        <label>Type Object</label>
    </fields>
    <fields>
        <name>Posted_in_Chatter__c</name>
        <help>Geeft aan of de fout is gepost in Chatter.</help>
        <label>Geplaatst in Chatter</label>
    </fields>
    <fields>
        <name>Record_URL__c</name>
        <help>Een koppeling naar de record die de fout veroorzaakte, indien beschikbaar.</help>
        <label>Record-URL</label>
    </fields>
    <fields>
        <name>Related_Record_ID__c</name>
        <help>De Salesforce-ID van de record die is gekoppeld aan deze fout.</help>
        <label>ID van gerelateerde record</label>
    </fields>
    <fields>
        <name>Retry_Pending__c</name>
        <help>Indien gesel., geeft dit aan dat de opgegeven record in ID van gerelateerde record weer wordt verwerkt in het volg. geplande proces. Als dit lukt, wordt het veld gedeselecteerd. Geldt ook voor specifieke fouten die plaatsvinden tijdens geplande processen.</help>
        <label>In behandeling opnieuw proberen?</label>
    </fields>
    <fields>
        <name>Stack_Trace__c</name>
        <help>Stack-tracering voor de geworpen fout, indien beschikbaar bij run-time.</help>
        <label>Stack-tracering</label>
    </fields>
</CustomObjectTranslation>
