<?xml version="1.0" encoding="UTF-8"?>
<CustomObjectTranslation xmlns="http://soap.sforce.com/2006/04/metadata">
    <layouts>
        <layout>Error Layout</layout>
        <sections>
            <label>Benutzerdefinierte Links</label>
            <section>Custom Links</section>
        </sections>
    </layouts>
    <nameFieldLabel>Fehlernummer</nameFieldLabel>
    <standardFields>
        <name>Name</name>
        <label>Fehlernummer</label>
    </standardFields>
    <gender>Masculine</gender>
    <caseValues>
        <plural>false</plural>
        <caseType>Nominative</caseType>
        <value>Fehler</value>
    </caseValues>
    <caseValues>
        <plural>false</plural>
        <caseType>Accusative</caseType>
        <value>Fehler</value>
    </caseValues>
    <caseValues>
        <plural>false</plural>
        <caseType>Dative</caseType>
        <value>Fehler</value>
    </caseValues>
    <caseValues>
        <plural>false</plural>
        <caseType>Genitive</caseType>
        <value>Fehlers</value>
    </caseValues>
    <caseValues>
        <plural>true</plural>
        <caseType>Nominative</caseType>
        <value>Fehler</value>
    </caseValues>
    <caseValues>
        <plural>true</plural>
        <caseType>Accusative</caseType>
        <value>Fehler</value>
    </caseValues>
    <caseValues>
        <plural>true</plural>
        <caseType>Dative</caseType>
        <value>Fehlern</value>
    </caseValues>
    <caseValues>
        <plural>true</plural>
        <caseType>Genitive</caseType>
        <value>Fehler</value>
    </caseValues>
    <fields>
        <name>Context_Type__c</name>
        <help>Kontext, der den Fehler verursacht hat, sofern bekannt</help>
        <label>Kontexttyp</label>
    </fields>
    <fields>
        <name>Datetime__c</name>
        <help>Datum und Uhrzeit bei Auftreten des Fehlers</help>
        <label>Datum/Uhrzeit</label>
    </fields>
    <fields>
        <name>Email_Sent__c</name>
        <help>Gibt an, ob zu diesem Fehler eine E-Mail-Benachrichtigung gesendet wurde</help>
        <label>E-Mail gesendet</label>
    </fields>
    <fields>
        <name>Error_Type__c</name>
        <help>Typ des aufgetretenen Fehlers</help>
        <label>Fehlertyp</label>
    </fields>
    <fields>
        <name>Full_Message__c</name>
        <help>Vollständiger Text der Fehlermeldung</help>
        <label>Vollständige Nachricht</label>
    </fields>
    <fields>
        <name>Object_Type__c</name>
        <help>Objekttyp, zu dem der Fehler aufgetreten ist, sofern bekannt</help>
        <label>Objekttyp</label>
    </fields>
    <fields>
        <name>Posted_in_Chatter__c</name>
        <help>Gibt an, ob der Fehler in Chatter gepostet wurde.</help>
        <label>Gepostet in Chatter</label>
    </fields>
    <fields>
        <name>Record_URL__c</name>
        <help>Link zum Datensatz, der den Fehler verursacht hat, sofern verfügbar.</help>
        <label>Datensatz-URL</label>
    </fields>
    <fields>
        <name>Related_Record_ID__c</name>
        <help>Die Salesforce-ID des Datensatzes, der diesem Fehler zugeordnet ist.</help>
        <label>Verwandte Datensatz-ID</label>
    </fields>
    <fields>
        <name>Retry_Pending__c</name>
        <help>Diese Option zeigt an, dass der Datensatz in &quot;Verwandte Datensatz-ID&quot; bei der nächsten planmäßigen Verarbeitung erneut verarbeitet wird. Gelingt dies, wird das Feld deaktiviert. Gilt für bestimmte Fehlertypen, die in geplanten Prozessen auftreten.</help>
        <label>Ausstehende wiederholen?</label>
    </fields>
    <fields>
        <name>Stack_Trace__c</name>
        <help>Stapelverfolgung für den ausgegebenen Fehler, falls bei Laufzeit verfügbar</help>
        <label>Stapelverfolgung</label>
    </fields>
</CustomObjectTranslation>
